### ISSUE TITLE
Sorry my actual URL is 'https://yts.It'

### ISSUE THREAD

**Issue by Pechi77** [rootVIII/proxy_requests#10]
Sorry my actual URL is 'https://yts.lt/'

_Originally posted by @Pechi77 in https://github.com/rootVIII/proxy_requests/issues/9#issuecomment-516940983_

**Comment by rootVIII** [comment]
Not sure about torrents unfortunately. You might need another library to download a magnet link.

**Comment by rootVIII** [comment]
I'm going to close this issue as I don't think it really applies to ProxyRequests. However this looks like it might be of use: https://stackoverflow.com/questions/39068376/how-to-apply-a-proxy-in-libtorrent The docs look pretty good too: https://www.libtorrent.org/python_binding.html
