### ISSUE TITLE
proxies are repeating

### ISSUE THREAD

**Issue by noskin9782** [rootVIII/proxy_requests#11]
is there a way to use every proxy once?
my code is like:

` 
     from proxy_requests import ProxyRequests

    while True:
    r = ProxyRequests("Censored")
    r.post({"Censored"})
    print(r)
    print(r.get_status_code())
    print(r.get_proxy_used())`

and output is like this:

`
91.92.80.25:40487

"CENSORED"

200

117.206.83.26:41960

"CENSORED"

400

117.206.83.26:41960

"CENSORED"

400

117.206.83.26:41960

"CENSORED"`

**Comment by rootVIII** [comment]
Ah yeah for each request there is a list of proxies used (they are scraped from the web). That list won't change until the source is changed/updated (when the website updates their proxies).

Give me a couple weeks or so (lots of stuff going on at work) and I will try to add something to fix that. It is possible to use the entire list: See #6 

But maybe I will try to add something to randomize or minimize repeated proxies. I'm mostly concerned with the proxy socket's health.

**Comment by rootVIII** [comment]
Ok proxies are randomized now so that should hopefully solve the issue
