### ISSUE TITLE
request get 

### ISSUE THREAD

**Issue by dimkoug** [rootVIII/proxy_requests#12]
Pass extra data to request get 

for example 

data = {'key': 1 , "key2":2}
r = ProxyRequests(url)
r.set_headers(headers)
r.get_with_headers()
r.get(data)

**Comment by rootVIII** [comment]
You can pass the headers with a Get request. But why pass data with a Get request? Not sure it’s something that is typically done.... https://stackoverflow.com/questions/978061/http-get-with-request-body/983458#983458

**Comment by dimkoug** [comment]
i have this code 

`import random
import requests
from proxy_requests.proxy_requests import ProxyRequests
from ipaddress import IPv4Address
base_url = ''
token  = ''

urls = [
    {'url':',
     'method':'get',
     'data': {'key': 'value', 'key2':'value2'},
     'headers': {'Authorization': 'Token {}'.format(token)}},
    {'url':',
     'method':'get',
     'data': {'key': 'value', 'key2':'value2'},
     'headers': {'Authorization': 'Token {}'.format(token)}},
]

def test_api(urls):
    for url in urls:
        print(url['url'])
        params = url['data']
        print(params)
        if url['method'] == 'post':
            r = ProxyRequests(url['url'])
            r.set_headers(url['headers'])
            r.post_with_headers(params)
            # r.post(params)
            #r = requests.post(url = url['url'],headers=url['headers'], params = params, proxies=proxy)
            data = r
        else:
            #r = ProxyRequests(url['url'])
            #r.set_headers(url['headers'])
            #r.get_with_headers()
            # r.get()
            r = requests.get(url = url['url'],headers=url['headers'], params = params)
            data = r.text
        print(data)

test_api(urls)
`

while post request work , get request not work

**Comment by rootVIII** [comment]
it's hard to tell by your code as it's not formatted... I was able to just run this though (I think it's similar to what you are trying).

```
from proxy_requests import ProxyRequests


def test_api(urls):
    for url in urls:
        if url['method'] == 'post':
            r = ProxyRequests(url['url'])
            r.set_headers(url['headers'])
            r.post_with_headers(url['data'])
        else:
            r = ProxyRequests(url['url'])
            r.set_headers(url['headers'])
            r.get_with_headers()
        yield r


if __name__ == '__main__':
    token = 'sometoken'
    url_data = [
        {
            'url': 'https://postman-echo.com/get?foo1=bar1&foo2=bar2',
            'method': 'get',
            'headers': {'Authorization': 'Token {}'.format(token)}},
        {
            'url': 'https://postman-echo.com/post',
            'method': 'post',
            'data': {'key': 'value', 'key2': 'value2'},
            'headers': {'Authorization': 'Token {}'.format(token)}},
    ]
    for d in test_api(url_data):
        print(d)

```

There's no option to pass a body with the GET request though as most servers won't understand it anyways.

**Comment by dimkoug** [comment]
thanks a lot !!!

**Comment by rootVIII** [comment]
No problem good luck
