### ISSUE TITLE
Unable to make proxied request... Please check the validity of link

### ISSUE THREAD

**Issue by deltaz3r0** [rootVIII/proxy_requests#13]
Hello, I am getting this message:
Unable to make proxied request... Please check the validity of https://graph.facebook.com/?id=https://www.ilpost.it/flashes/video-foto-gruppo-berlino&fields=og_object{engagement}

However, when I check it, the link is fine.

When I print out the proxy used, what I get is blank. 

It seems to work only when I set the headers.

**Comment by rootVIII** [comment]
Hi there... was the request to ipify? I noticed it looks like they may be blocking Anonymous Proxies now. Can you try with a different URL?

**Comment by deltaz3r0** [comment]
Hey, the request was to facebook's graph API, but it seemed to work once the headers were set. 

However, after something like 500 requests to the API I get an Application Limit Notice (from the API), so I'm assuming the limit has been hit on all the proxies?

**Comment by b-a0** [comment]
I get the same error with a different target URL (an API for fleetbird), but if I keep repeating the request at some point it does get me a valid response. What might be causing this?

**Comment by rootVIII** [comment]
I just pushed an update that raises the timeout, and allows all proxies in the pool to be used/attempt to be used. This should solve the 'Unable to make proxied request' as long as your IP is valid. Also, I've added some exception raising so that it might be easier to identify errors. I'm going to randomize the IP addresses so that there is less of a chance of hitting API limits due to the same proxy being used (however the list does get refreshed regularly).

**Comment by rootVIII** [comment]
Okay proxies are also randomized now in 0.3.7 so that should solve the other issue.

**Comment by deltaz3r0** [comment]
Hello again, I ran the code that I ran when I created this issue (when the version was `0.3.5`).
I have now updated to the most recent version (`0.4.0`) but I can't seem to get even 1 request through, as I immediately get a "Proxy Pool" has been emptied exception. 
This happens when I set the headers, when they are not set it seems to work fine for 20 requests, then the ` HTTPSConnectionPool(host='graph.facebook.com', port=443): Read timed out. (read timeout=3.0)` exception gets risen and interrupts the program.

I feel like it's good that you are better specifying the issue, but maybe raise the error as a message instead of an exception like you did in `0.3.5`?

**Comment by rootVIII** [comment]
Ah can you try the latest one? There is a 0.4.1 now. I may get rid of the exception handling as the traceback is large. But the timeout is at 8 seconds in the new version, and will hopefully fix it.

**Comment by rootVIII** [comment]
Yup I just tried to use get_with_headers() and it seems okay....

**Comment by deltaz3r0** [comment]
Seems to be working fine now! Thank you for solving this issue. Not really sure of why the headers were causing the Empty Proxy Pool exception, but now it's working fine. I'll let you know if I encounter any other issues - thank you for solving them so quickly!

**Comment by rootVIII** [comment]
Sure man sorry about that. Each request may take a little longer now as the proxies are randomized (therefore the healthiest proxies may not get selected first). But should be all set now. Thanks for bringing up the issue
