### ISSUE TITLE
Reduced size of sockets list

### ISSUE THREAD

**Issue by DerHamm** [rootVIII/proxy_requests#14]
Rather a question than an issue: I have read that you have reduced the size of sockets to be parsed from sslproxies. I'm curios why as I first thought that the regex was faulty.

**Comment by rootVIII** [comment]
I was attempting to grab the newest proxies listed on their page. Unfortunately a lot of them still take some time foe the request to go through. I can add back the rest of the proxies tonight?

**Comment by DerHamm** [comment]
All right, but you don't have to. I was just curious.

**Comment by rootVIII** [comment]
I shall put the entire list back I think. I am also working on a solution for getting only the strongest/best proxies available for the next update.

**Comment by rootVIII** [comment]
Changes added. It should return all proxies now. Going to push to pypi right now... 0.4.3

**Comment by DerHamm** [comment]
If you want you can take a look at my fork for getting only the strongest proxies. You can set ProxyRequests.anoymity to e.g. filter only elite servers.

**Comment by rootVIII** [comment]
Well that's a good idea, but when I say strongest I mean response time? Some of those servers will hang and hang. That is why I set a timeout for each request. If it takes too long then give up and try the next. 

I don't care so much if it's ELITE or ANONYMOUS (although I agree that elite is much better, and your check is pretty cool too). But really I want to eliminate the ones that have a really slow response time.

I have both a threaded and an asynch solution that checks all the proxies inside the ProxyRequests() init/constructor. Basically all the proxies that are too slow get eliminated.

I haven't pushed the changes for this yet as sometimes there are way too many slow servers and only a handful of fast ones. But I will most likely have it working good and will push for the next update....
