### ISSUE TITLE
get method is returning None instead of any actual content

### ISSUE THREAD

**Issue by tjblue** [rootVIII/proxy_requests#16]
Example code I was running:
`r = ProxyRequests('https://www.google.com')`

`print(r.get())`
>None

Any suggestions?

**Comment by rootVIII** [comment]
Did you try any other URLs? Google is pretty good at blocking Anonymous proxies. This probably won’t work for any Google affiliated sites either, including youtube. You’ll have the same issues using Tor and trying to access Google as well.

**Comment by tjblue** [comment]
I did try with other sites. https://httpbin.org/ip didn't work even though it does when I use the normal requests.get() with proxies I pull off sslproxies manually. How many proxy addresses does the class go through before it quits? I'm really doing anonymous API stuff so I wasn't actually using GET for google. The API has let me use 'manual' proxies before. Kind of a mind-bender.

**Comment by tjblue** [comment]
It looks like when get() is used it only writes to the rdata dict with  _set_requests_data() and doesn't actually return any string or text.

def get(self):

        if len(self.sockets) > 0:
            current_socket = self.sockets.pop(self._rand_sock())
            proxies = {
                'http': 'http://' + current_socket,
                'https': 'https://' + current_socket
            }
            try:
                request = requests.get(
                    self.url,
                    timeout=self.rdata['timeout'],
                    proxies=proxies)
                self._set_request_data(request, current_socket)
            except Exception as e:
                self._is_err(e)
                self.get()
Correct me if I'm wrong, I'm still new to coding.
Is there a different part that is like: return self.rdata['request']?

**Comment by tjblue** [comment]
LOL! Nevermind. You did put that in there the __str__() method does literally what I just asked. Thank you!
