### ISSUE TITLE
responsed url

### ISSUE THREAD

**Issue by hrf3** [rootVIII/proxy_requests#17]
Hi,
I am missing the possibility to get the responsed url like response.request.url in Python’s Requests Library. I can't find this info in headers or html.text.

**Comment by rootVIII** [comment]
Oh I can add that in the next update. Thanks!

**Comment by rootVIII** [comment]
Okay added a get_url() method in 0.4.9.

```
>>> from proxy_requests import ProxyRequests
>>> r = ProxyRequests('https://api.ipify.org')
>>> r.get()
>>> r.get_url()
'https://api.ipify.org/'
```

**Comment by hrf3** [comment]
Works fine, thanks.
Think about doku, please.
