### ISSUE TITLE
Automatically modifies and breaks text data

### ISSUE THREAD

**Issue by Wissotsky** [rootVIII/proxy_requests#18]
It modifies text body into a json body
if I want to send this in the body

something=somethingelse

it sends

"something=somethingelse"

Which breaks certain websites

**Comment by rootVIII** [comment]
Can you give a sample of how you are using it?

Are you looking to send with the `data= ` attribute ?

EDIT: Also I'm unsure what you are attempting. It "looks" like you might be needing URL parameters... which should still work just fine.
