### ISSUE TITLE
KeyError: 'request'

### ISSUE THREAD

**Issue by faaafo** [rootVIII/proxy_requests#21]
Python 3.9.1 (default, Dec 13 2020, 11:55:53) 

```python
from proxy_requests import ProxyRequests
url = "https://api.ipify.org/"
r = ProxyRequests(url)
print(r)
```
    --------------------------------------------------
    KeyError         Traceback (most recent call last)
    <ipython-input-9-c6b8a6a9416b> in <module>
    ----> 1 print(r)
    
    ~/.local/lib/python3.9/site-packages/proxy_requests/proxy_requests.py in __str__(self)
        202 
        203     def __str__(self):
    --> 204         return str(self.rdata['request'])
        205 
        206 
    
    KeyError: 'request'

**Comment by rootVIII** [comment]
Yes I can confirm this. Going to close this as it's the same issues as #20
