### ISSUE TITLE
Not getting the status code and proxy used.

### ISSUE THREAD

**Issue by amreshgiri-coditas** [rootVIII/proxy_requests#3]
I'm not able to get the status code and proxy IP which is used. Its printing blank lines.

**Comment by rootVIII** [comment]
Hi there:

I noticed that you didn't actually perform the GET before asking for the status code (although I can't see your code any more?): 
```
>>> from proxy_requests.proxy_requests import ProxyRequests 
>>> r = ProxyRequests("https://github.com/rootVIII")
>>> r.get()
>>> r.get_status_code()
200
```

Just make sure you actually GET the url with r.get() before asking for the status code.
