### ISSUE TITLE
[Feature request]: get_with_headers

### ISSUE THREAD

**Issue by awarebayes** [rootVIII/proxy_requests#4]
It is crucial to have UserAgent headers for some sites to work. I spend an hour debugging and trying to find what's wrong and it turned out that there is no get method with headers support 
```
    def get_with_headers(self):
        if len(self.sockets) > 0:
            current_socket = self.sockets.pop(0)
            proxies = {"http": "http://" + current_socket, "https": "https://" + current_socket}
            try:
                request = requests.get(self.url, timeout=3.0, proxies=proxies, headers=self.headers)
                self.request = request.text
                self.headers = request.headers
                self.status_code = request.status_code
                self.proxy_used = current_socket
            except:
                print('working...')
                self.get_with_headers()
```

**Comment by rootVIII** [comment]
thanks for letting me know... adding it right now... just tested and it's working. Will update repo in several moments...

**Comment by rootVIII** [comment]
I'm going to close this now. The repo has been updated and I will push changes to Pypi as well in a few seconds. Here's an example that will work:

```
>>> h = {"User-Agent": "NCSA Mosaic/3.0 (Windows 95)"}
>>> r = ProxyRequests("url goes here")
>>> r.set_headers(h)
>>> r.get_with_headers()

```
Thanks again for pointing that out

**Comment by awarebayes** [comment]
Also, that would be cool not to copy every field from requests.request to the ProxyRequests object. For example, I want to load a picture from some website, it's stored into request.content, but never gets copied into your wrapper class.

This part is bad code:
```
request = requests.get(self.url, timeout=3.0, proxies=proxies)
self.request = request.text
self.headers = request.headers
self.status_code = request.status_code
self.proxy_used = current_socket
```
A good solution I see would be to add .raw field storing the requests object:
`self.raw = request`

**Comment by rootVIII** [comment]
I always just use the class to get JSON mostly... but I don’t see why that can’t be added as well. I’ll add changes by tonight most likely. Thanks again

**Comment by rootVIII** [comment]
Ok it's been added... there's now a ```response_to_file()``` method... works for images, as well as text/HTML and JSON...

In the near future I may remove  ```self.request = request.text``` and just use the raw content for everything... also going to add a get_raw() method in a moment in case you want to write the file yourself.
