### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by Pechi77** [rootVIII/proxy_requests#9]
I am trying to scrap a site which is blocked by my isp.

my code 
from proxy_requests import ProxyRequests 

```
r = ProxyRequests(url)
r.get()
```
output
`Unable to make proxied request... Please check the validity of https://httpbin.org/ip
`

**Comment by rootVIII** [comment]
Is that the actual URL that you are using?

Seems to work fine for me. It should for you too...

```
>>> from proxy_requests import ProxyRequests 
>>> url = 'https://httpbin.org/ip'
>>> r = ProxyRequests(url)
>>> r.get()
>>> r.get_status_code()
200
>>> r.get_proxy_used()
'188.235.149.170:35609'
>>> print(r)
{
  "origin": "188.235.149.170, 188.235.149.170"
}
```

**Comment by rootVIII** [comment]
I typically will only see that error that you have shown if the URL is not valid, or if I am not connected to the internet. Are you on a corporate LAN? EDIT: After poking around some... I see that Pastebin is blocked by many ISPs. Unfortunately I think it is possible for your ISP to also block requests coming from anonymous proxies (and responses too).

Are you able to use other technologies... like Tor? I'm curious.  If you can use Tor... you might be able to use torsocks with wget to achieve a download... similar to this:

https://github.com/rootVIII/wgettor

if you were to just run a single bash command it would look something like

` torsocks wget -q --user-agent=<some useragent> <url>`

**Comment by Pechi77** [comment]
Sorry my actual URL is 'https://yify.It'
